// Generated by gencpp from file dronestack/OpticalFlow.msg
// DO NOT EDIT!


#ifndef DRONESTACK_MESSAGE_OPTICALFLOW_H
#define DRONESTACK_MESSAGE_OPTICALFLOW_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dronestack
{
template <class ContainerAllocator>
struct OpticalFlow_
{
  typedef OpticalFlow_<ContainerAllocator> Type;

  OpticalFlow_()
    : header()
    , OptF_x(0.0)
    , OptF_y(0.0)
    , OptF_z(0.0)  {
    }
  OpticalFlow_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , OptF_x(0.0)
    , OptF_y(0.0)
    , OptF_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _OptF_x_type;
  _OptF_x_type OptF_x;

   typedef float _OptF_y_type;
  _OptF_y_type OptF_y;

   typedef float _OptF_z_type;
  _OptF_z_type OptF_z;





  typedef boost::shared_ptr< ::dronestack::OpticalFlow_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dronestack::OpticalFlow_<ContainerAllocator> const> ConstPtr;

}; // struct OpticalFlow_

typedef ::dronestack::OpticalFlow_<std::allocator<void> > OpticalFlow;

typedef boost::shared_ptr< ::dronestack::OpticalFlow > OpticalFlowPtr;
typedef boost::shared_ptr< ::dronestack::OpticalFlow const> OpticalFlowConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dronestack::OpticalFlow_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dronestack::OpticalFlow_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dronestack::OpticalFlow_<ContainerAllocator1> & lhs, const ::dronestack::OpticalFlow_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.OptF_x == rhs.OptF_x &&
    lhs.OptF_y == rhs.OptF_y &&
    lhs.OptF_z == rhs.OptF_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dronestack::OpticalFlow_<ContainerAllocator1> & lhs, const ::dronestack::OpticalFlow_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dronestack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dronestack::OpticalFlow_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dronestack::OpticalFlow_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dronestack::OpticalFlow_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dronestack::OpticalFlow_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dronestack::OpticalFlow_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dronestack::OpticalFlow_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dronestack::OpticalFlow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "170905b60a5f60e2e27710db96379516";
  }

  static const char* value(const ::dronestack::OpticalFlow_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x170905b60a5f60e2ULL;
  static const uint64_t static_value2 = 0xe27710db96379516ULL;
};

template<class ContainerAllocator>
struct DataType< ::dronestack::OpticalFlow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dronestack/OpticalFlow";
  }

  static const char* value(const ::dronestack::OpticalFlow_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dronestack::OpticalFlow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# OpticalFlow.msg\n"
"Header header\n"
"float32 OptF_x\n"
"float32 OptF_y\n"
"float32 OptF_z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dronestack::OpticalFlow_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dronestack::OpticalFlow_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.OptF_x);
      stream.next(m.OptF_y);
      stream.next(m.OptF_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpticalFlow_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dronestack::OpticalFlow_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dronestack::OpticalFlow_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "OptF_x: ";
    Printer<float>::stream(s, indent + "  ", v.OptF_x);
    s << indent << "OptF_y: ";
    Printer<float>::stream(s, indent + "  ", v.OptF_y);
    s << indent << "OptF_z: ";
    Printer<float>::stream(s, indent + "  ", v.OptF_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONESTACK_MESSAGE_OPTICALFLOW_H
