// Generated by gencpp from file dronestack/waypoint_navResponse.msg
// DO NOT EDIT!


#ifndef DRONESTACK_MESSAGE_WAYPOINT_NAVRESPONSE_H
#define DRONESTACK_MESSAGE_WAYPOINT_NAVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dronestack
{
template <class ContainerAllocator>
struct waypoint_navResponse_
{
  typedef waypoint_navResponse_<ContainerAllocator> Type;

  waypoint_navResponse_()
    : success(false)  {
    }
  waypoint_navResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::dronestack::waypoint_navResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dronestack::waypoint_navResponse_<ContainerAllocator> const> ConstPtr;

}; // struct waypoint_navResponse_

typedef ::dronestack::waypoint_navResponse_<std::allocator<void> > waypoint_navResponse;

typedef boost::shared_ptr< ::dronestack::waypoint_navResponse > waypoint_navResponsePtr;
typedef boost::shared_ptr< ::dronestack::waypoint_navResponse const> waypoint_navResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dronestack::waypoint_navResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dronestack::waypoint_navResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dronestack::waypoint_navResponse_<ContainerAllocator1> & lhs, const ::dronestack::waypoint_navResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dronestack::waypoint_navResponse_<ContainerAllocator1> & lhs, const ::dronestack::waypoint_navResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dronestack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dronestack::waypoint_navResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dronestack::waypoint_navResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dronestack::waypoint_navResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dronestack::waypoint_navResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dronestack::waypoint_navResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dronestack::waypoint_navResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dronestack::waypoint_navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::dronestack::waypoint_navResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::dronestack::waypoint_navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dronestack/waypoint_navResponse";
  }

  static const char* value(const ::dronestack::waypoint_navResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dronestack::waypoint_navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::dronestack::waypoint_navResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dronestack::waypoint_navResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct waypoint_navResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dronestack::waypoint_navResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dronestack::waypoint_navResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONESTACK_MESSAGE_WAYPOINT_NAVRESPONSE_H
