// Generated by gencpp from file dronestack/waypoint_nav.msg
// DO NOT EDIT!


#ifndef DRONESTACK_MESSAGE_WAYPOINT_NAV_H
#define DRONESTACK_MESSAGE_WAYPOINT_NAV_H

#include <ros/service_traits.h>


#include <dronestack/waypoint_navRequest.h>
#include <dronestack/waypoint_navResponse.h>


namespace dronestack
{

struct waypoint_nav
{

typedef waypoint_navRequest Request;
typedef waypoint_navResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct waypoint_nav
} // namespace dronestack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dronestack::waypoint_nav > {
  static const char* value()
  {
    return "522b662e714d54037c689130a0d58075";
  }

  static const char* value(const ::dronestack::waypoint_nav&) { return value(); }
};

template<>
struct DataType< ::dronestack::waypoint_nav > {
  static const char* value()
  {
    return "dronestack/waypoint_nav";
  }

  static const char* value(const ::dronestack::waypoint_nav&) { return value(); }
};


// service_traits::MD5Sum< ::dronestack::waypoint_navRequest> should match
// service_traits::MD5Sum< ::dronestack::waypoint_nav >
template<>
struct MD5Sum< ::dronestack::waypoint_navRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dronestack::waypoint_nav >::value();
  }
  static const char* value(const ::dronestack::waypoint_navRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dronestack::waypoint_navRequest> should match
// service_traits::DataType< ::dronestack::waypoint_nav >
template<>
struct DataType< ::dronestack::waypoint_navRequest>
{
  static const char* value()
  {
    return DataType< ::dronestack::waypoint_nav >::value();
  }
  static const char* value(const ::dronestack::waypoint_navRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dronestack::waypoint_navResponse> should match
// service_traits::MD5Sum< ::dronestack::waypoint_nav >
template<>
struct MD5Sum< ::dronestack::waypoint_navResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dronestack::waypoint_nav >::value();
  }
  static const char* value(const ::dronestack::waypoint_navResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dronestack::waypoint_navResponse> should match
// service_traits::DataType< ::dronestack::waypoint_nav >
template<>
struct DataType< ::dronestack::waypoint_navResponse>
{
  static const char* value()
  {
    return DataType< ::dronestack::waypoint_nav >::value();
  }
  static const char* value(const ::dronestack::waypoint_navResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONESTACK_MESSAGE_WAYPOINT_NAV_H
